### ISSUE TITLE
SM is doing property injection when not expected

### ISSUE THREAD

**Issue by stigc** [structuremap/structuremap#318]
Is this behaviour as expected?
Version 3.1.4.143

```
using NUnit.Framework;
using StructureMap;
using StructureMap.Configuration.DSL;
namespace Test
{
    public class TestStructureMapRegistry : Registry
    {
        public TestStructureMapRegistry()
        {
            For<MyService1>().Use<MyService1>()
                    .Ctor<MyDependency>("dep1").Is(new MyDependency())
                    .Ctor<MyDependency>("dep2").Is(new MyDependency());

            For<MyService2>().Use<MyService2>()
                    .Ctor<MyDependency>("dep1").Is(new MyDependency())
                    .Ctor<MyDependency>("dep2").Is(new MyDependency());
        }
    }

    public class MyDependency
    {
    }

    public class MyService1
    {
        public MyDependency Dep1 { get; set; }
        public MyDependency Dep2 { get; set; }

        public MyService1(MyDependency dep1, MyDependency dep2)
        {
            this.Dep1 = dep1;
            this.Dep2 = dep2;
        }
    }

    public class MyService2
    {
        MyDependency dep1, dep2;

        public MyDependency Dep1 { get { return dep1; }}
        public MyDependency Dep2 { get { return dep2; }}

        public MyService2(MyDependency dep1, MyDependency dep2)
        {
            this.dep1 = dep1;
            this.dep2 = dep2;
        }
    }

    class SmBehaviourTest
    {
        public void Test()
        {
            var container = new Container(configure => configure.AddRegistry<TestStructureMapRegistry>());

            var service1 = container.GetInstance<MyService1>();
            Assert.AreSame(service1.Dep1, service1.Dep2);

            var service2 = container.GetInstance<MyService2>();
            Assert.AreNotSame(service2.Dep1, service2.Dep2);
        }
    }
}
```

**Comment by jeremydmiller** [comment]
@stigc I'm looking at this right now.

**Comment by jeremydmiller** [comment]
@stigc It's a bug. It'll be in 3.1.5 shortly.

**Comment by jeremydmiller** [comment]
@stigc It's the confluence of settable properties of the same type as the constructor argument. If you remove the setter on Service1, you're fine. Because StructureMap *can* find an explicit dependency for the public setter type, it's assumed that you mean to set that. 

I'm not sure that I want to introduce any extra complexity here to eliminate the secondary Setter injection. See the comment in the commit to this bug.

**Comment by stigc** [comment]
HI Jeremy, thanks for looking into it.

I thought property injection should be enabled!? So if I configure a String in the container for a specific Constructor argument, every public string property would be set to this instance? 

Structuremap 2.6.4.1 did not have this behaviour.

**Comment by stigc** [comment]
Yes it's an easy workaround, but also easy to miss

**Comment by jeremydmiller** [comment]
2.6.4.1 did have optional setter injection, i.e., if the dependency was configured for a public setter, it would set it.

3.* changed the way it stored and attached explicitly defined dependencies in a single bag for the Instance. In your particular case that turned out to be harmful because your setters had public set's. Idiomatic usage would be for everything coming in from the container to be readonly.
