### ISSUE TITLE
StructureMap and the Composite pattern

### ISSUE THREAD

**Issue by jvandertil** [structuremap/structuremap#426]
Hello,

I'm trying to use the Composite pattern with StructureMap, and to my knowledge this always worked. But for some reason I can't get it to work properly anymore. 

The error is a StructureMap.Building.StructureMapBuildException: Bi-directional dependency relationship detected.

Simplified code sample:
```c#
public interface IFoo 
{
  void Action();
}

public class Foo : IFoo
{
  public void Action() 
  {
    // Something here.
  }
}

public class CompositeFoo : IFoo
{
  private readonly IEnumerable<IFoo> _foos;

  public CompositeFoo(IEnumerable<IFoo> foos)
  {
    _foos = foos;
  }

  public void Action()
  {
    foreach(var foo in _foos) 
    {
      foo.Action();
    }
  }
}

public static IContainer GetContainer() 
{
  var container = new Container(cfg => {
    cfg.Scan(scan => {
      scan.TheCallingAssembly();

      scan.AddAllTypesOf<IFoo>();
      scan.ExcludeType<CompositeFoo>();
    });

    cfg.For<IFoo>().Use<CompositeFoo>();
  });

  return container;
}

public void Test() {
  var container = GetContainer();

  var foo = container.GetInstance<IFoo>();
}

```

Fiddle: https://dotnetfiddle.net/IkGAyB

**Comment by jeremydmiller** [comment]
@jvandertil,

Your registration code is still adding `CompositeFoo` as an `IFoo` from the call to `For<IFoo>().Use<CompositeFoo>(), and hence, the bi-directional relationship.

**Comment by jvandertil** [comment]
Hmm, so how would I inject a CompositeFoo when I require an IFoo on a constructor?

**Comment by jvandertil** [comment]
@jeremydmiller 

I solved it with the following configuration:

```c#
var container = new Container(cfg => {
    cfg.For<IFoo>()
       .Use<CompositeFoo>()
       .EnumerableOf<IFoo>().Contains(x => x.Type<Foo>());
  });
```

Which is fine actually, if I want to do more advanced stuff I can always look at using MEF. But since I don't need that flexibility I'm ok with specifying the dependencies explicitly.

**Comment by jeremydmiller** [comment]
@jvandertil MEF, seriously? StructureMap can do this just fine, it's just that you have to be a touch smarter about the registration. You probably could have solved the issue faster if you'd looked at the diagnostics -- which don't exist in MEF. If you wanna just use MEF, then you deserve everything you're going to get.

**Comment by jvandertil** [comment]
@jeremydmiller I'm not using MEF (and won't use it if I can avoid it), I'm still using StructureMap. I just couldn't figure out how to register the Composite properly when combined with scanning. If you have an example of how it can be done, please show me.

**Comment by julealgon** [comment]
> @jvandertil MEF, seriously? StructureMap can do this just fine, it's just that you have to be a touch smarter about the registration. You probably could have solved the issue faster if you'd looked at the diagnostics -- which don't exist in MEF. If you wanna just use MEF, then you deserve everything you're going to get.

What's up with such offensive reply @jeremydmiller ? I mean... even if you don't like MEF, there was no reason to insult it and to insult the OP as well, which provided a very valid question.

Anyways... I'd really appreciate if there was a clean way of registering a composite pattern in StructureMap as well. I've just hit this problem and decided to go with an explicit `IChildDoSomething` interface to avoid hardcoding all registrations. Very far from ideal, since I'm introducing an interface that is exactly the same as `IDoSomething` just because the container doesn't have a clean generic support for "ignoring one registration" for `IEnumerable` resolution.

If there was a way to tell "ok, this is the main implementation for the interface, *and don't provide it when someone asks for a list*", then that would be perfect. Another option would be to provide something to disallow recursive injections: that would prevent the framework from attempting to inject the composite into itself.

**Could you please reconsider this and add something to the framework to allow us to have a clean composite pattern?**

**Comment by jeremydmiller** [comment]
@julealgon So yes, this comes up a time or two a year. 

"Could you please reconsider this and add something to the framework to allow us to have a clean composite pattern?"

**I would happily take in a pull request for this behavior.**
