### ISSUE TITLE
Types created from Closed Implementation of Generic is the same instance

### ISSUE THREAD

**Issue by jcteague** [structuremap/structuremap#432]
When a type is registered by  Closing A Generic Implementation, and used a parameter to two other objects, the same instance is used.  Here is a Test:

[InstanceTests.cs.txt](https://github.com/structuremap/structuremap/files/101682/InstanceTests.cs.txt)

I was expecting a different instance of the closed type in each consuming object

**Comment by jeremydmiller** [comment]
@jcteague,

As far as I can tell from your sample, that is expected behavior. See [Object Lifecycles](http://structuremap.github.io/object-lifecycle/) in the docs for an exact explanation of SM's lifecycle support. You might wanna be using the "AlwaysUnique" lifecycle for your case as an alternative.

- Jeremy

**Comment by jcteague** [comment]
Yep, That worked.  Thanks
