### ISSUE TITLE
Use of Paket causes NuGet Pack to fail with XML exception.

### ISSUE THREAD

**Issue by StuartBaker65** [structuremap/structuremap#474]
In writing a simple library that uses structuremap.automocking I could not use the "NuGet Pack" until structuremap.automocking reference was removed.

The error manifests itself as an XML exception thus:
`CategoryInfo : NotSpecified: (System.Xml.XmlE... 2, position 2.:String) [], RemoteException`

Initially I raised this against NuGet, but the problem seems to be inherent in the structuremap.automocking library. For a full explanation see: #https://github.com/NuGet/Home/issues/2718#issuecomment-217515915

To quote toddm:

> The structuremap.automocking package was created by using paket.exe instead of NuGet.exe. The standard .NET zip package code is throwing the XML exception trying to read the package properties. There doesn't seem to be a NuGet bug here. It seems to be that the packages are bad.
I'd suggest you contact the package owner and suggest they pack using NuGet.exe instead

FYI: I have contacted the authors of Paket

**Comment by jeremydmiller** [comment]
@StuartBaker65 If I did anything w/ automocking, it would probably be to either make it a source code only package or to finally write some docs on how to set it up your self w/o the Nuget. I've been wanting to discontinue this nuget for quite a while anyway.

All but the mock library specific adapter code is in the main StructureMap.dll anyway.

**Comment by forki** [comment]
I'm looking at the issue right now.

**Comment by forki** [comment]
I assume it's built with some older pakt version that contained a bug (see https://github.com/NuGet/Home/issues/2718#issuecomment-217908567) repacaking the same package with latest paket should give a correct coreProp.psmdcp file inside the package. Sorry for the inconvenience.

**Comment by ErikxNilsson** [comment]
Hi, 

This is also a problem with structuremap-signed and structuremap.web-signed version 3.1.6.191, the reason nuget.exe v3+ fails is what forki wrote above, the file /package/services/metadata/core-properties/[guid].psmcdp contains <Relationships> as the root element instead of <coreProperties>

Note that nuget.exe v2.8.x will work just fine.

**Comment by forki** [comment]
Is this a paket issue? Did you raise an issue? Would like to know details
and help.

**Comment by ErikxNilsson** [comment]
Its this exact error, but in one of the other structuremap packages, so it seemed most appropriate to add here instead of raising a separate issue.
The generated .nupkg files for packages http://www.nuget.org/packages/structuremap.web-signed/3.1.6.191 and http://www.nuget.org/packages/structuremap-signed/3.1.6.191 have invalid content (according to nuget 3.x) in the file /package/services/metadata/core-properties/*.psmcdp (guid-named file).
Nuget 2.x seem more forgiving for this and do not cause an error.

**Comment by forki** [comment]
Is there  a chance to republish the packages with latest paket. IIRC we fixed that pacakging issue already.

**Comment by jeremydmiller** [comment]
Should be fixed now, or at least it's published with the latest.
