### ISSUE TITLE
StructureMap instantiate NameValueCollection

### ISSUE THREAD

**Issue by sachpatel** [structuremap/structuremap#475]
I have just started using StructureMap. I am having an issue with instantiating an object that requires a NameValueCollection as a dependency via a constructor.

The error I receive is:
`
StructureMap.StructureMapConfigurationException
No default Instance is registered and cannot be automatically determined for type 'System.Collections.IHashCodeProvider'
`
I should not need to provide IoC setup for the IHashCodeProvider that is needed by the NameValueCollection.

In my case I was passing in the `ConfigurationManager.AppSettings` object as the substitute for the NameValueCollection argument.

I have created a unit test that reproduces the issue on a branch called [NVC_DependencyResolution](https://github.com/sachpatel/structuremap/tree/NVC_DependencyResolution) and it is a single commit consisting of the test 'use_a_custom_constructor_selector_requiring_empty_nvc'. 

Could somebody help?

**Comment by jeremydmiller** [comment]
"I should not need to provide IoC setup for the IHashCodeProvider that is needed by the NameValueCollection."
 
-- StructureMap - or any other IoC container - is not magic. It isn't going to know how to fulfill the `NameValueCollection` unless you teach it how. By default, it's looking at your class that takes in `NameValueCollection` and assuming that it has to resolve that to the default NameValueCollection. When SM tries to figure out how to build NameValueCollection, the ctor selection settles on the "richest" ctor for that that takes in `IHashCodeProvider` and that's why you landed here. 

In your case, you could explicitly register the ConfigurationManager.AppSettings as the default NameValueCollection, or use that as an inline dependency for whatever type it is that you're trying to resolve like this: http://structuremap.github.io/registration/inline-dependencies/.


Would you close this issue if you're satisfied with the answer?

**Comment by sachpatel** [comment]
Thanks for your help
