### ISSUE TITLE
Each<T> function inaccessible due to its protection level

### ISSUE THREAD

**Issue by antwilliams** [structuremap/structuremap#508]
I am slowly working my way through the documentation for StructureMap and figuring out how we can apply it to our projects.

I have noticed something in the new [registration policies](http://structuremap.github.io/registration/policies/) and in the example for setting up [contextual logging](http://structuremap.github.io/the-container/working-with-the-icontext-at-build-time/).

The .Each<T> method used in the examples is part of the internal [StringExtensions](https://github.com/structuremap/structuremap/blob/master/src/StructureMap/Extensions.cs) class and I am unable to use it.

Am I missing something obvious here (another extension function) or is this an error!?

Regards,
Anthony

**Comment by jeremydmiller** [comment]
It's just an extension method used throughout the StructureMap codebase. If you want it, Baseline has that extension method. Or just opt into foreach.

**Comment by antwilliams** [comment]
I found the extension method in the main codebase, I just wondered if the fact that the class was internal was deliberate given that it was used to extensively in the documentation.

**Comment by jeremydmiller** [comment]
There's literally something like 10,000 extension methods in Github that implement that exact same Each() or ForEach() iteration. I didn't want it colliding with other folks libraries.

**Comment by Joebeazelman** [comment]
I chose StructureMap because the syntax was very straightforward given the examples. When I sat down to experiment with it, however, I encountered the same compilation error.  This is a classic case of bad documentation!  You could have used ForEach() in your examples or at the very least warned the innocent developer of whatever may befall them when using this library.

A conflict error would have been infinitely more informative.  If the Each() extension method is part of another library, the assembly should have been included as part of the package.  If it was part of StructureMap, VS would allow the developer to fully qualify the namespace for that extension.

This issue shouldn't be marked closed because it hasn't been properly resolved.

**Comment by jeremydmiller** [comment]
@Joebeazelman I take pull requests
