### ISSUE TITLE
Calling CreateFactory results in FileNotFoundException in .net core

### ISSUE THREAD

**Issue by hisuwh** [structuremap/structuremap#559]
I am trying use Structuremap.AutoFactory in a .net core application.

I have Structuremap working but when I added a registration with `.CreateFactory()` I now get System.IO.FileNotFoundException.

Is this a bug?  Or any ideas how to fix this?

![image](https://cloud.githubusercontent.com/assets/4470351/24605606/619b62e8-1861-11e7-8788-13e8043aa285.png)

**Comment by jeremydmiller** [comment]
@hisuwh Hey, can you tell me a little bit more about your environment? Was this .Net 4.6 or a CoreCLR targeted project? Are you using VS2017 by chance, because that's way, way more temperamental about Nuget than previous versions. Do you actually have the StructureMap nuget installed to this project?

**Comment by jeremydmiller** [comment]
@hisuwh Hey, would you mind updating to the very latest nugets and see if it gets better?

```
New nugets are up for StructureMap 4.4.4, AutoFactory 1.0.1, and DynamicInterception 1.0.2. Try those and see if the binding problems go away?
```

**Comment by hisuwh** [comment]
Thanks for the response @jeremydmiller 

CoreCLR currently, yes 2017 and the structuremap nuget is installed in this project.

I will update the versions shortly and test this thanks

**Comment by hisuwh** [comment]
Yes this solves my issue.  Thanks
